---
title: "ASITA workshop"
date: "`r format(Sys.Date(), '%d %b %Y')`"
number-sections: true
number-offset: 0
toc: true
toc-depth: 2
fig-width: 6
fig-height: 4
df-print: kable
embed-resources: true
format: 
  html: 
    highlight-style: dracula
    code-tools: true
    code-fold: show
    code-summary: "Show the code"
    code-line-numbers: true
    code-link: true # only works if code-line-numbers: false
    toc-float: true
  docx: 
    toc-title: "Table of contents"
    fig-dpi: 600
    execute:
      echo: false
knitr: 
  opts_chunk: 
    fig.path: "plots/"
    fig.keep: "all"
    dev: ['png', 'pdf']
    dev.args: 
      pdf: 
        encoding: 'WinAnsi'
        useDingbats: false
crossref:
  fig-prefix: Fig.
  tbl-prefix: Table
  ref-hyperlink: true
editor: source
---

# Setup

Using `r R.version.string` and isoreader `r packageVersion("isreader2")`.

```{r}
#| label: setup
#| message: false

# load packages
library(isoreader2)
library(ggplot2)
```

# Data

```{r}
# load data
```

